package Pharmachain.service.impl;

import Pharmachain.dto.BillRequestDto;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class BillPdfService {

    public byte[] generateBillPdf(BillRequestDto bill) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        Document document = new Document();
        PdfWriter.getInstance(document, out);
        document.open();

        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

        document.add(new Paragraph(bill.getPharmacyName(), titleFont));
        document.add(new Paragraph("Customer: " + bill.getCustomerName(), normalFont));
        document.add(new Paragraph("Date: " + new java.util.Date(), normalFont));
        document.add(Chunk.NEWLINE);

        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);

        table.addCell("Medicine");
        table.addCell("Qty");
        table.addCell("Price");

        bill.getItems().forEach(item -> {
            table.addCell(item.getMedicineName());
            table.addCell(String.valueOf(item.getQuantity()));
            table.addCell("₹" + item.getPrice());
        });

        document.add(table);
        document.add(Chunk.NEWLINE);
        document.add(new Paragraph("Total Amount: ₹" + bill.getTotalAmount(), titleFont));
        document.add(Chunk.NEWLINE);
        document.add(new Paragraph("Generated by PharmaChain", normalFont));

        document.close();
        return out.toByteArray();
    }
}